const AuthActionTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
}

export default AuthActionTypes
