const productsActionTypes = {
  SORT_NAME: 'SORT_NAME',
  GET_PRODUCTS_START: 'GET_PRODUCTS_START',
  SORT_PRICE: 'SORT_PRICE',
  SET_CURRENCY: 'SET_CURRENCY',
  TOGGLE_PRODUCTS_LOADING: 'TOGGLE_PRODUCTS_LOADING',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  PRODUCTS_OPERATION_FAILURE: 'PRODUCTS_OPERATION_FAILURE',
  HAS_MORE_PRODUCTS_TOGGLE: 'HAS_MORE_PRODUCTS_TOGGLE',
}

export default productsActionTypes
